# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.IntegerField()),
                ('district', models.CharField(blank=True, default='', max_length=32)),
                ('school_id', models.IntegerField()),
                ('school', models.CharField(blank=True, default='', max_length=65)),
                ('academic_year', models.IntegerField()),
                ('subject', models.CharField(blank=True, default='', max_length=21)),
                ('subgroup', models.CharField(blank=True, default='', max_length=32)),
                ('grade_level', models.CharField(blank=True, default='', max_length=3)),
                ('participation_rate_2014_to_2015', models.DecimalField(decimal_places=1, max_digits=3)),
                ('percentage_meets_or_exceeds_2014_to_2015', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                'ordering': ('school',),
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField()),
                ('school', models.CharField(blank=True, default='', max_length=60)),
                ('district_id', models.IntegerField()),
                ('district', models.CharField(blank=True, default='', max_length=46)),
            ],
            options={
                'ordering': ('school',),
            },
        ),
    ]
